### PR TITLE
Fix: co-authors not cleared from message template (`.gitmessage`) on switch from mob to solo

### PR DESCRIPTION
**Pull request by teezzan**
This PR contains the following fixes:
- Removal of all instances where co-authors are written to `~/.gitmessage`. 
- Added feature spec of mob feature.
@davidalpert Please check it out.

### CODE REVIEW

**Comment by davidalpert** [comment]
this looks good and the change is along the lines I had in mind.

there is something broken in the build scripts however; the feature tests failed and the build still passed. I am looking into that and will get back to you later today.

**Review by davidalpert — CHANGES_REQUESTED** [review]
@teezzan thank you for your contribution! 

Your code change in [8b5c24f](https://github.com/davidalpert/go-git-mob/pull/89/commits/8b5c24f08b533bd00dbe3746f9af0621a53f3234) looks good.

I have a couple of notes about the testing and PR checks that I want us to address before merging your change:
1. the test pattern in this repo includes both golang unit tests and also ruby/cucumber acceptance tests
1. the unit tests pass with your code change but the acceptance tests fail since there are currently some acceptance tests around the `.gitmessage` file
1. the checks in this PR didn't fail due to #90 which I investigated and fixed this morning
1. the `.feature` file you added here appears to be testing that the core function of adding the Co-Authored-By tag still works after your change; this behavior is already covered by many other tests so you can remove it.
    - here is an example of the kind of test I was thinking to write before making any changes, demonstrating expected behavior and failing because of this bug: https://github.com/davidalpert/go-git-mob/pull/92
    - note that [this step](https://github.com/davidalpert/go-git-mob/pull/92/files#diff-a4774c2f54377313ac56db18b18e15c8b79b5b4b2ebc6a8284e0a82a26a0e806R32-R36) and others like it in other feature files will need to be removed in order to pass with [8b5c24f](https://github.com/davidalpert/go-git-mob/pull/89/commits/8b5c24f08b533bd00dbe3746f9af0621a53f3234)

Requested changes:
- [ ] remove `features/git-mob/mob-init-persists-coauthor.feature`
- [ ] please rebase on top of `bug-feature-example` (from #92) to pick up the PR build fixes and that example feature file demonstrating the bug
- [ ] run all the tests locally and fix broken specs by removing all the feature expectations that `~/.gitmessage` reflects the mob members

**Comment by davidalpert** [comment]
@teezzan do you think you will have time to get to the requested changes this month?

if not, I can approve this PR as-is (since the code change resolves the bug) and then resolve any failed tests as housekeeping.

**Comment by teezzan** [comment]
On it, @davidalpert . Sorry for being AWOL.

**Review by davidalpert — APPROVED** [review]

**Pull request merged**
